666PRJ/CookingCurator

CookingCurator/Controllers/Manager.cs, CookingCurator/Controllers/UserController.cs, CookingCurator/CookingCurator.csproj, CookingCurator/EntityModels/UserBaseViewModel.cs, CookingCurator/EntityModels/UserFindViewModel.cs, CookingCurator/Views/User/Index.cshtml, CookingCurator/Views/User/Search.cshtml
This adds functionally to search users
=> Search User 

CookingCurator/Controllers/Manager.cs, CookingCurator/Controllers/UserController.cs, CookingCurator/EntityModels/UserBaseViewModel.cs, CookingCurator/Views/User/Index.cshtml
Ban User is a option on the index menu and can be called to ban/unban a user.
=> Implemented ban user

CookingCurator/Controllers/ProfileController.cs, CookingCurator/CookingCurator.csproj, CookingCurator/Views/Profile/Dashboard.cshtml, CookingCurator/Views/Profile/UserDashboard.cshtml
Admin and User dashboards menus created
=> Dashboards updated

CookingCurator/Controllers/Manager.cs, CookingCurator/Controllers/ReferencesController.cs, CookingCurator/CookingCurator.csproj, CookingCurator/EntityModels/RecipeSourceViewModel.cs, CookingCurator/Views/References/Index.cshtml
This adds a page that lists all of our sources.
Let me know if I'm missing anything.
=> Added references page

CookingCurator/Controllers/Manager.cs, CookingCurator/Controllers/RecipeController.cs, CookingCurator/CookingCurator.csproj, CookingCurator/EntityModels/IngredBaseViewModel.cs, CookingCurator/EntityModels/RecipeAddViewModel.cs, CookingCurator/Models/DataContext.cs, CookingCurator/Views/Recipe/CreateVerified.cshtml
This has all of the code for recipes but lacks ingred support. 
I'll merge it in for now
=> Add Recipe 

CookingCurator/Controllers/Manager.cs, CookingCurator/Controllers/RecipeController.cs, CookingCurator/Controllers/UserController.cs, CookingCurator/CookingCurator.csproj, CookingCurator/Views/Home/About.cshtml, CookingCurator/Views/Home/Index.cshtml, CookingCurator/Views/Profile/Dashboard.cshtml, CookingCurator/Views/Profile/UserDashboard.cshtml, CookingCurator/Views/Recipe/Authors.cshtml, CookingCurator/Views/Recipe/Details.cshtml, CookingCurator/Views/Shared/_Layout.cshtml, CookingCurator/Views/User/Details.cshtml, CookingCurator/Views/User/Index.cshtml, CookingCurator/Views/User/Search.cshtml
Two views added, one under 'Recipe' and one under 'User'.   Dashboards were also updated and some minor changes made to existing views for new links to these pages.
=> Recipe Listing for an author added.  Dashboards updated.

CookingCurator/Models/ALLERGY_INGREDS.cs, CookingCurator/Models/DIET_INGREDS.cs, CookingCurator/Models/DataContext.cs, CookingCurator/Models/Model1.Context.cs, CookingCurator/Models/Model1.Designer.cs, CookingCurator/Models/Model1.edmx, CookingCurator/Models/Model1.edmx.diagram, CookingCurator/Models/RECIPE_USERS.cs
This updates the db.
I did a little testing but I think most of should work.
=> Updated db

CookingCurator/App_Start/IdentityConfig.cs, CookingCurator/Controllers/HomeController.cs, CookingCurator/Controllers/Manager.cs, CookingCurator/Controllers/ProfileController.cs, CookingCurator/Controllers/RecipeController.cs, CookingCurator/CookingCurator.csproj, CookingCurator/EntityModels/LoginViewModel.cs, CookingCurator/Models/DataContext.cs, CookingCurator/Models/IdentityRole.cs, CookingCurator/Models/IdentityUser.cs, CookingCurator/Models/SiteRole.cs, CookingCurator/Views/Home/Index.cshtml, CookingCurator/Views/Home/Login.cshtml, CookingCurator/Web.config, CookingCurator/packages.config
This implements login and roles to our app.
Let me know if anything should be Admin only and I'll add it.
=> Login/Roles Implementation 

CookingCurator/Controllers/HomeController.cs, CookingCurator/Controllers/Manager.cs, CookingCurator/CookingCurator.csproj, CookingCurator/EntityModels/RegisterViewModel.cs, CookingCurator/Models/Model1.Context.cs, CookingCurator/Models/Model1.edmx, CookingCurator/Models/Model1.edmx.diagram, CookingCurator/Models/USER.cs, CookingCurator/Views/Home/Register.cshtml, CookingCurator/Web.config
This Registers new user. Remember to sign out if you want to create a new one
=> Register User

CookingCurator/Controllers/HomeController.cs, CookingCurator/Controllers/Manager.cs, CookingCurator/Controllers/RecipeController.cs, CookingCurator/CookingCurator.csproj, CookingCurator/EntityModels/IngredBaseViewModel.cs, CookingCurator/EntityModels/LoginViewModel.cs, CookingCurator/EntityModels/RecipeAddViewModel.cs, CookingCurator/EntityModels/RecipeBaseViewModel.cs, CookingCurator/EntityModels/RecipeSourceViewModel.cs, CookingCurator/EntityModels/Recipe_IngredViewModel.cs, CookingCurator/EntityModels/RegisterViewModel.cs, CookingCurator/EntityModels/UserBaseViewModel.cs, CookingCurator/EntityModels/UserFindViewModel.cs, CookingCurator/Views/Home/Index.cshtml, CookingCurator/Views/Home/Login.cshtml, CookingCurator/Views/Home/Register.cshtml, CookingCurator/Views/Home/RegisterationSuccess.cshtml, CookingCurator/Views/Home/TestAcc.cshtml, CookingCurator/Views/Home/VerifyAccount.cshtml, CookingCurator/Views/Profile/ContactUs.cshtml, CookingCurator/Views/Profile/Dashboard.cshtml, CookingCurator/Views/Profile/UserDashboard.cshtml, CookingCurator/Views/Recipe/Create.cshtml, CookingCurator/Views/Recipe/CreateVerified.cshtml, CookingCurator/Views/Recipe/Details.cshtml, CookingCurator/Views/Recipe/Edit.cshtml, CookingCurator/Views/Recipe/Index.cshtml, CookingCurator/Views/User/Index.cshtml, CookingCurator/Views/User/Search.cshtml
Please review to make sure no functionality from Master branch was lost.
Added link to page with info for professor to log in and for references.  Added link to log out and register.
One element name has to be hard coded ("Ingredients" on recipe details page)
=> Clean headings 3

CookingCurator/Controllers/Manager.cs, CookingCurator/Controllers/SearchController.cs, CookingCurator/CookingCurator.csproj, CookingCurator/EntityModels/SearchViewModel.cs, CookingCurator/Views/Search/Search.cshtml
This adds basic functionality for search
=> Search By Ingred

CookingCurator/Controllers/HomeController.cs, CookingCurator/Controllers/Manager.cs, CookingCurator/CookingCurator.csproj, CookingCurator/EntityModels/LoginViewModel.cs, CookingCurator/EntityModels/RecoverViewModel.cs, CookingCurator/Views/Home/Forgot.cshtml, CookingCurator/Views/Home/Login.cshtml, CookingCurator/Views/Home/Reset.cshtml
To recover a password, the email must verified and not banned.
=> Added Password Recovery and Reset

CookingCurator/Controllers/SearchController.cs, CookingCurator/Controllers/UserController.cs
This adds admin and user authorization to a couple of different views
=> Update user and admin access

CookingCurator/Controllers/Manager.cs, CookingCurator/Controllers/ProfileController.cs, CookingCurator/CookingCurator.csproj, CookingCurator/EntityModels/ChangePasswordViewModel.cs, CookingCurator/EntityModels/ChangeUsernameViewModel.cs, CookingCurator/Views/Profile/ChangePassword.cshtml, CookingCurator/Views/Profile/ChangeUsername.cshtml
Adds the ability to change username/password
=> Change username/password

CookingCurator/Controllers/Manager.cs, CookingCurator/Controllers/UserController.cs
This adds ban user functionality to the rest of the app.
=> Updated Ban User

CookingCurator/Controllers/Manager.cs, CookingCurator/Controllers/SearchController.cs, CookingCurator/EntityModels/SearchViewModel.cs, CookingCurator/Views/Search/Search.cshtml
This adds a feature to search by title.
=> Added Search by Title

CookingCurator/Controllers/HomeController.cs, CookingCurator/Views/Home/Index.cshtml, CookingCurator/Views/Profile/UserDashboard.cshtml
This adds some missing button functionality and also makes some small formatting changes
=> Normalize website

CookingCurator/Controllers/Manager.cs, CookingCurator/Controllers/RecipeController.cs, CookingCurator/Views/Recipe/Index.cshtml
User will be able to filter recipes by country, meal time type and verified check and can also use all three filters in a single search
=> User can filter recipes 

CookingCurator/Views/Profile/ChangePassword.cshtml, CookingCurator/Views/Profile/ChangeUsername.cshtml, CookingCurator/Views/Profile/Dashboard.cshtml, CookingCurator/Views/Profile/UserDashboard.cshtml, CookingCurator/Views/Recipe/Index.cshtml, CookingCurator/Views/Search/Search.cshtml, CookingCurator/Views/Shared/_Layout.cshtml
Removed 'viewmodel' titles, fixed some links, and made it some most links do not appear on navigation bar until logged in.
=> Fixed some page text and links

CookingCurator/Controllers/SearchController.cs, CookingCurator/Views/Search/Search.cshtml
This should fix the bug with the route details
=> Updated search by Title

CookingCurator/Controllers/Manager.cs, CookingCurator/Controllers/RecipeController.cs, CookingCurator/EntityModels/IngredientBaseViewModel.cs, CookingCurator/EntityModels/RecipeAddViewModel.cs, CookingCurator/EntityModels/RecipeBaseViewModel.cs, CookingCurator/Views/Recipe/Create.cshtml, CookingCurator/Views/Recipe/Details.cshtml, CookingCurator/Views/Recipe/Index.cshtml
Only people who created recipe will be able to edit and delete there own.
Also fixes recipe add
=> Recipe Ownership

CookingCurator/Controllers/DietController.cs, CookingCurator/Controllers/Manager.cs, CookingCurator/Controllers/RecipeController.cs, CookingCurator/CookingCurator.csproj, CookingCurator/EntityModels/DietDescViewModel.cs, CookingCurator/Views/Diet/Index.cshtml, CookingCurator/Views/Profile/UserDashboard.cshtml, CookingCurator/Views/Recipe/Authors.cshtml, CookingCurator/Views/Recipe/Diet.cshtml
Added two pages for diets and recipes per diet.
=> Added two diet pages

CookingCurator/Controllers/ProfileController.cs, CookingCurator/CookingCurator.csproj, CookingCurator/Views/Profile/AdminDoc.cshtml, CookingCurator/Views/Profile/UserDoc.cshtml
This is my initial documentation for Admins/Users.
Let me know if any of this information is wrong or needs to be changed
=> Added User/Admin Doc

CookingCurator/Controllers/AllergyController.cs, CookingCurator/Controllers/Manager.cs, CookingCurator/CookingCurator.csproj, CookingCurator/EntityModels/AllergyViewModel.cs, CookingCurator/Views/Allergy/Index.cshtml, CookingCurator/Views/Allergy/Ingredient.cshtml, CookingCurator/Views/Profile/UserDashboard.cshtml, CookingCurator/Views/Shared/_Layout.cshtml
Allergy Index and 'Ingredients per Allergy' pages added.  Also hid two navbar links for non-admins.
Currently, some of the 'Ingredients per Allergy' pages display no ingredients or duplicate ingredients.  These are database issues and should be resolved sometime in the near future.
=> two pages for allergies added, hid certain links for users

CookingCurator/Views/Home/Index.cshtml, CookingCurator/Views/Home/Register.cshtml, CookingCurator/Views/Recipe/Index.cshtml, CookingCurator/Views/Search/Search.cshtml, CookingCurator/Views/Shared/_Layout.cshtml
I made a couple of of minor UI tweaks.
=> More UI improvements

CookingCurator/Controllers/SearchController.cs, CookingCurator/Views/Search/Search.cshtml
Should no longer break when imputing no items
=> Fixed Search

CookingCurator/Controllers/Manager.cs
This should change author username
=> Update change username

CookingCurator/Controllers/Manager.cs, CookingCurator/Controllers/RecipeController.cs, CookingCurator/EntityModels/Recipe_IngredViewModel.cs, CookingCurator/Views/Recipe/Create.cshtml, CookingCurator/Views/Recipe/CreateVerified.cshtml, CookingCurator/Views/Recipe/Edit.cshtml
and added the note regarding the image size and fixed the deleting all ingredients issue
=> Fixed the editing recipe issue 

CookingCurator/Controllers/AllergyController.cs, CookingCurator/Controllers/BookmarkController.cs, CookingCurator/Controllers/DietController.cs, CookingCurator/Controllers/HomeController.cs, CookingCurator/Controllers/Manager.cs, CookingCurator/Controllers/ProfileController.cs, CookingCurator/Controllers/RecipeController.cs, CookingCurator/Controllers/ReferencesController.cs, CookingCurator/Controllers/SearchController.cs
This should log out users.
Let me know if I am missing something or something needs to change.
=> Should log out user if they are logged in

CookingCurator/Views/Recipe/Details.cshtml
Please review this PR and ignore the previous one. I've made the source link clickable
=> Recipe details ui

CookingCurator/Controllers/HomeController.cs, CookingCurator/Controllers/Manager.cs, CookingCurator/Controllers/ProfileController.cs, CookingCurator/Views/Home/Register.cshtml, CookingCurator/Views/Profile/ChangeUsername.cshtml
This adds error message for space in username.
=> Fix #79 : Error message for space in username

CookingCurator/Controllers/Manager.cs
This should fix https://github.com/666PRJ/CookingCurator/issues/92.
=> Added is banned check

CookingCurator/Controllers/Manager.cs, CookingCurator/Models/Model1.edmx
and a unique salt will be created for each user
=> Password will be now encrypted

CookingCurator/Controllers/Manager.cs, CookingCurator/Controllers/RecipeController.cs, CookingCurator/EntityModels/RecipeBaseViewModel.cs, CookingCurator/Views/Recipe/Details.cshtml
This adds recommend recipes to the details page
=> Added Recommended

CookingCurator/Controllers/Manager.cs
Fixed https://github.com/666PRJ/CookingCurator/issues/95
=> Fixed #95 : No usernames in use

CookingCurator/Controllers/RecipeController.cs, CookingCurator/CookingCurator.csproj, CookingCurator/EntityModels/ReportRecipeViewModel.cs, CookingCurator/Views/Recipe/Index.cshtml, CookingCurator/Views/Recipe/ReportRecipe.cshtml
Also moved ReportRecipeViewModel to EntityModels
=> Showing arrow whether the sort is ascending or descending

CookingCurator/Controllers/HomeController.cs, CookingCurator/Controllers/Manager.cs, CookingCurator/Controllers/ProfileController.cs, CookingCurator/Controllers/RecipeController.cs, CookingCurator/Controllers/SearchController.cs, CookingCurator/CookingCurator.csproj, CookingCurator/Views/Home/AcceptWaiver.cshtml, CookingCurator/Views/Profile/ContactUs.cshtml, CookingCurator/Views/Recipe/Create.cshtml, CookingCurator/Views/Recipe/CreateVerified.cshtml, CookingCurator/Views/Recipe/Details.cshtml, CookingCurator/Views/Recipe/Edit.cshtml, CookingCurator/Views/Shared/_AcceptWaiver.cshtml
and increase width of some input elements and added a check for 50 bookmarks
=> Added new layout for AcceptWaiver 

CookingCurator/Controllers/Manager.cs, CookingCurator/Controllers/ProfileController.cs, CookingCurator/Controllers/RecipeController.cs, CookingCurator/CookingCurator.csproj, CookingCurator/EntityModels/ChangeAllergiesViewModel.cs, CookingCurator/EntityModels/ChangeDietsViewModel.cs, CookingCurator/Models/DataContext.cs, CookingCurator/Views/Profile/ChangeAllergies.cshtml, CookingCurator/Views/Profile/ChangeDiets.cshtml, CookingCurator/Views/Profile/UserDashboard.cshtml
Selecting diets on the "Set Diets" page, effects which recipes are shown on the "Recipe Index" page
Having no diets selected means the recipe index displays all recipes.
=> Diets effect recipe index

CookingCurator/Controllers/Manager.cs, CookingCurator/Controllers/ProfileController.cs, CookingCurator/CookingCurator.csproj, CookingCurator/EntityModels/ChangeAllergiesViewModel.cs, CookingCurator/EntityModels/ChangeDietsViewModel.cs, CookingCurator/Models/DataContext.cs, CookingCurator/Views/Profile/ChangeAllergies.cshtml, CookingCurator/Views/Profile/ChangeDiets.cshtml, CookingCurator/Views/Profile/UserDashboard.cshtml
Users can save a list of Diets and Allergies on the 'Set Diets' and 'Set Allergies' pages
Additional functionality using saved lists will be added in a future PR.
=> Added the Set Diets and Set Allergies pages

CookingCurator/Controllers/HomeController.cs, CookingCurator/Controllers/Manager.cs
This fixes https://github.com/666PRJ/CookingCurator/issues/104.
=> Fixed #104: Error for username/email in use

CookingCurator/Controllers/SearchController.cs, CookingCurator/Views/Search/Search.cshtml
=> Fixed #108 : Updated search ui

CookingCurator/Views/Home/About.cshtml, CookingCurator/Views/Home/Index.cshtml, CookingCurator/Views/Profile/UserDoc.cshtml, CookingCurator/Views/References/Index.cshtml
This updates docs and references
=> FAQ and Reference Updates

CookingCurator/Controllers/Manager.cs, CookingCurator/Views/Recipe/Details.cshtml
This limits recommendations, let me know if I'm missing anything
=> Fixed #116 : Limited recommendations

CookingCurator/Controllers/Manager.cs, CookingCurator/Controllers/RecipeController.cs, CookingCurator/EntityModels/RecipeAddViewModel.cs, CookingCurator/EntityModels/Recipe_IngredViewModel.cs
Should prevent creation of and editing recipes without ingredients without crashes
Should allow creating and editing recipes while giving them no diets.
=> Should fix create and edit recipes issues

CookingCurator/Controllers/RecipeController.cs, CookingCurator/Views/Recipe/Create.cshtml, CookingCurator/Views/Recipe/CreateVerified.cshtml, CookingCurator/Views/Recipe/Details.cshtml, CookingCurator/Views/Recipe/Edit.cshtml
we will be able to present instructions in a better way
=> Added the rich text editor

CookingCurator/Controllers/Manager.cs, CookingCurator/Controllers/RecipeController.cs, CookingCurator/Views/Profile/ChangeAllergies.cshtml
If a user has selected allergies, the recipes on the recipe index page will be limited to those that don't contain the allergens of that allergy.
If a user has diets AND allergies selected, both are taken into account.
Cow's Milk allergy is good to use for testing.
=> Allergies now effect recipe index page

CookingCurator/Views/Profile/ContactUs.cshtml, CookingCurator/Views/Profile/DeleteAccount.cshtml
This fixes https://github.com/666PRJ/CookingCurator/issues/132.
=> Fixes Links

CookingCurator/Controllers/Manager.cs, CookingCurator/Controllers/ProfileController.cs, CookingCurator/Views/Profile/ChangeUsername.cshtml
Also, fixes a error with empty username
Fixes https://github.com/666PRJ/CookingCurator/issues/126.
=> Fixed #126: Better Error Message

CookingCurator/Controllers/ProfileController.cs, CookingCurator/Controllers/SearchController.cs
This changes the error message for password
=> Changed Error Password Style

CookingCurator/EntityModels/UserBaseViewModel.cs, CookingCurator/Views/User/Index.cshtml
This fixes https://github.com/666PRJ/CookingCurator/issues/133.
=> Fixes #133: Adds email verified 

CookingCurator/Controllers/Manager.cs, CookingCurator/Controllers/RecipeController.cs, CookingCurator/Controllers/UserController.cs, CookingCurator/EntityModels/RecipeBaseViewModel.cs, CookingCurator/Views/Recipe/Details.cshtml
This fixes https://github.com/666PRJ/CookingCurator/issues/127.
=> Fixed #127: Adds Link to author

CookingCurator/Controllers/Manager.cs, CookingCurator/Controllers/ProfileController.cs, CookingCurator/Controllers/RecipeController.cs, CookingCurator/CookingCurator.csproj, CookingCurator/EntityModels/ChangeRestrictionsViewModel.cs, CookingCurator/Models/DataContext.cs, CookingCurator/Views/Profile/ChangeRestrictions.cshtml, CookingCurator/Views/Profile/UserDashboard.cshtml, CookingCurator/Views/Recipe/Details.cshtml
Custom restrictions are now in place.
Effects what appears on recipe listing page alongside selected Diets and Allergies (if any)
Also added minor warning to bottom of recipe detail pages
=> Ingredient restrictions added

CookingCurator/Views/Bookmark/Index.cshtml
This fixes https://github.com/666PRJ/CookingCurator/issues/143
=> Fixed #143:added thumbs to bookmark

CookingCurator/Controllers/RecipeController.cs
This fixes https://github.com/666PRJ/CookingCurator/issues/145.
=> Fixed #145: Added better error message

CookingCurator/Controllers/RecipeController.cs
This fixes https://github.com/666PRJ/CookingCurator/issues/148.
=> Fixed #148: Added validation for edit recipe

CookingCurator/Views/Recipe/Details.cshtml
This should fix https://github.com/666PRJ/CookingCurator/issues/152.
=> Fixed 152: Added non user recipes to details

CookingCurator/Views/Bookmark/Index.cshtml
This fixes https://github.com/666PRJ/CookingCurator/issues/144.
=> Fix #144: Added links to bookmarks

CookingCurator/Views/User/Details.cshtml
This removes contact user and makes minor changes.
This fixes https://github.com/666PRJ/CookingCurator/issues/130.
=> Fix #130: Updated user details

CookingCurator/Controllers/Manager.cs, CookingCurator/Controllers/ProfileController.cs, CookingCurator/EntityModels/ChangeUsernameViewModel.cs, CookingCurator/Models/USER.cs, CookingCurator/Views/Profile/ChangeUsername.cshtml
This fixes https://github.com/666PRJ/CookingCurator/issues/145.
Also, fixes issue with ban user.
=> Fix #145: Error with change username

CookingCurator/Controllers/Manager.cs, CookingCurator/Controllers/RecipeController.cs
This allows spaces for special characters
=> Fixed Space Issue

CookingCurator/Controllers/Manager.cs, CookingCurator/Views/References/Index.cshtml
This fixes https://github.com/666PRJ/CookingCurator/issues/172.
This fixes https://github.com/666PRJ/CookingCurator/issues/178.
=> Fixed #172: Added another reference

CookingCurator/Controllers/Manager.cs
This fixes https://github.com/666PRJ/CookingCurator/issues/181.
=> Fixes bookmark bug

CookingCurator/Controllers/Manager.cs, CookingCurator/Controllers/RecipeController.cs, CookingCurator/CookingCurator.csproj, CookingCurator/Views/Recipe/Index.cshtml
This fixes https://github.com/666PRJ/CookingCurator/issues/185.
=> Sorting can be done by date

CookingCurator/Controllers/BookmarkController.cs, CookingCurator/Controllers/Manager.cs, CookingCurator/Views/Bookmark/Index.cshtml, CookingCurator/Views/Shared/_Layout.cshtml
Also removed redundant links from the nav bar
This fixes https://github.com/666PRJ/CookingCurator/issues/177
=> User able to delete all bookmarks

CookingCurator/Controllers/Manager.cs, CookingCurator/Controllers/RecipeController.cs, CookingCurator/Views/Recipe/Create.cshtml, CookingCurator/Views/Recipe/CreateVerified.cshtml, CookingCurator/Views/Recipe/Edit.cshtml
This PR fixes https://github.com/666PRJ/CookingCurator/issues/184.
=> Fixed #184: Lessened restrictions

CookingCurator/Controllers/Manager.cs
This Fixes https://github.com/666PRJ/CookingCurator/issues/198.
It should fix the sorting issue by trimming
=> Fixed 198: fixed sorting issue

CookingCurator/Views/Recipe/Create.cshtml, CookingCurator/Views/Recipe/CreateVerified.cshtml, CookingCurator/Views/Recipe/Edit.cshtml
This fixes a bug with Create Recipe
=> Fixed Create Recipe Bug

CookingCurator/Controllers/Manager.cs, CookingCurator/Controllers/ProfileController.cs, CookingCurator/Views/User/Index.cshtml
This PR adds more warnings to change username/change password/delete account
=> Added More Warnings

CookingCurator/Controllers/HomeController.cs, CookingCurator/EntityModels/RegisterViewModel.cs
This updates register user error messages
=> Updated Error Messages

CookingCurator/Controllers/RecipeController.cs
This adds an additional error message for recipe
=> Recipe Update

CookingCurator/Views/Profile/AdminDoc.cshtml, CookingCurator/Views/Profile/UserDoc.cshtml
Text changes for the Documentation pages.  No other changes
=> Doc text update
